version: 2
updates:
  # Enable version updates for Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    # Reviewers for Go dependency updates
    reviewers:
      - "tasius"  # Replace with your GitHub username
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
